// 每日佳句資料庫(近百年的現代名人)。句子數量 = 循環週期(天)。新增只需在陣列末尾加一行。
// zh: 中文(翻譯)  en: 英文原句  by: 「中文名 English name」  ig: Instagram 帳號(選填)
window.QUOTES = [
  // —— Naval Ravikant ——
  { zh: "要追求財富，不是金錢，也不是地位。財富，就是那些你睡覺時還在幫你賺錢的資產。", en: "Seek wealth, not money or status. Wealth is having assets that earn while you sleep.", by: "納瓦爾·拉維坎特 Naval Ravikant" },
  { zh: "學會銷售，也學會做出東西。兩個都會，你就誰都擋不住。", en: "Learn to sell. Learn to build. If you can do both, you will be unstoppable.", by: "納瓦爾·拉維坎特 Naval Ravikant" },
  { zh: "專屬知識，就是沒辦法靠上課學會的知識。", en: "Specific knowledge is knowledge you cannot be trained for.", by: "納瓦爾·拉維坎特 Naval Ravikant" },
  { zh: "挑一個行業，跟願意長期合作的人，一起玩長期的遊戲。", en: "Pick an industry where you can play long-term games with long-term people.", by: "納瓦爾·拉維坎特 Naval Ravikant" },
  { zh: "慾望，就是你跟自己簽的約：想要的東西沒到手之前，你就是不快樂。", en: "Desire is a contract you make with yourself to be unhappy until you get what you want.", by: "納瓦爾·拉維坎特 Naval Ravikant" },
  { zh: "用腦袋賺錢，不要用時間換錢。", en: "Earn with your mind, not your time.", by: "納瓦爾·拉維坎特 Naval Ravikant" },
  { zh: "讀你喜歡的書，讀到你愛上閱讀為止。", en: "Read what you love until you love to read.", by: "納瓦爾·拉維坎特 Naval Ravikant" },
  { zh: "靈感很容易消失，有了就馬上去做。", en: "Inspiration is perishable—act on it immediately.", by: "納瓦爾·拉維坎特 Naval Ravikant" },
  { zh: "想避開競爭，就做你自己。", en: "Escape competition through authenticity.", by: "納瓦爾·拉維坎特 Naval Ravikant" },
  { zh: "平靜的心、健康的身體、充滿愛的家，這些用錢買不到，只能自己去爭取。", en: "A calm mind, a fit body, a house full of love. These things cannot be bought. They must be earned.", by: "納瓦爾·拉維坎特 Naval Ravikant" },
  { zh: "程式和媒體，是不用誰點頭就能用的槓桿。", en: "Code and media are permissionless leverage.", by: "納瓦爾·拉維坎特 Naval Ravikant" },
  { zh: "別理那些愛玩地位遊戲的人。他們靠攻擊創造財富的人，來抬高自己的地位。", en: "Ignore people playing status games. They gain status by attacking people playing wealth creation games.", by: "納瓦爾·拉維坎特 Naval Ravikant" },

  // —— Dan Koe ——
  { zh: "如果你不自己選一種奮鬥，生活就會幫你選一個。", en: "If you don't choose a struggle, you will be assigned one.", by: "丹·寇 Dan Koe", ig: "thedankoe" },
  { zh: "如果你不知道自己要什麼，別人就會告訴你該要什麼，而你還會相信。", en: "If you don't know what you want, you will be told what you want, and you will believe it.", by: "丹·寇 Dan Koe", ig: "thedankoe" },
  { zh: "如果你不自己訂目標，就會被別人安排一個。", en: "If you don't create a purpose, you will be assigned one.", by: "丹·寇 Dan Koe", ig: "thedankoe" },
  { zh: "逼自己走進不舒服的環境，這樣到了五十歲，心智才不會還像十五歲。", en: "Force yourself into uncomfortable situations so you don't end up being 50 years old with the emotional maturity of a 15 year old.", by: "丹·寇 Dan Koe", ig: "thedankoe" },
  { zh: "沒有什麼比「看看自己到底能做到什麼」更值得花一輩子去做。", en: "There doesn't seem to be a more worthwhile endeavor to dedicate your life to than to see what you are capable of.", by: "丹·寇 Dan Koe", ig: "thedankoe" },
  { zh: "沒有什麼比你的潛力更重要。不是手機，不是電視，也不是任何現在正在勾你注意力的東西。", en: "Nothing is more important than your potential. Not your phone, not the TV, not anything that is begging to stimulate your brain's reward system right now.", by: "丹·寇 Dan Koe", ig: "thedankoe" },
  { zh: "光靠想，解決不了需要動手才能解決的問題。", en: "No amount of thinking is going to fix the problem that is solved by doing.", by: "丹·寇 Dan Koe", ig: "thedankoe" },
  { zh: "比追求最好的自己更難的，就是不去追求最好的自己。", en: "The only thing more challenging than pursuing the highest version of yourself is not pursuing the highest version of yourself.", by: "丹·寇 Dan Koe", ig: "thedankoe" },

  // —— Alex Hormozi ——
  { zh: "開出一個好到對方拒絕了會覺得自己很傻的條件。", en: "Make people an offer so good they would feel stupid saying no.", by: "亞歷克斯·霍爾莫齊 Alex Hormozi", ig: "hormozi" },
  { zh: "價格是你付出的，價值是你得到的。", en: "Price is what you pay. Value is what you get.", by: "亞歷克斯·霍爾莫齊 Alex Hormozi", ig: "hormozi" },
  { zh: "痛點，就是你的賣點。", en: "The pain is the pitch.", by: "亞歷克斯·霍爾莫齊 Alex Hormozi", ig: "hormozi" },
  { zh: "人怕失去的心，比想得到的心還要強。", en: "Fear of loss is stronger than desire for gain.", by: "亞歷克斯·霍爾莫齊 Alex Hormozi", ig: "hormozi" },
  { zh: "提供最多價值的公司，就會贏。就是這樣。", en: "The business that provides the most value wins. Period.", by: "亞歷克斯·霍爾莫齊 Alex Hormozi", ig: "hormozi" },
  { zh: "不求回報地幫助別人，會更有成就感、更長壽，也賺得更多。", en: "People who help others (with zero expectation) experience higher levels of fulfillment, live longer, and make more money.", by: "亞歷克斯·霍爾莫齊 Alex Hormozi", ig: "hormozi" },
  { zh: "開始做內容最好的時間是你出生那天，第二好的時間就是現在。", en: "The best day to start posting content was the day you were born. The second best day is today.", by: "亞歷克斯·霍爾莫齊 Alex Hormozi", ig: "hormozi" },
  { zh: "別在意別人怎麼想。如果有人不會在你的告別式上說話，你活著的時候就不用在乎他的意見。", en: "Don't be afraid of what other people think. If someone won't speak at your funeral, you shouldn't care about their opinion while you're alive.", by: "亞歷克斯·霍爾莫齊 Alex Hormozi", ig: "hormozi" },

  // —— 其他現代作者與創業家 ——
  { zh: "你不會因為目標而變強，你只會掉回你的系統能做到的水準。", en: "You do not rise to the level of your goals. You fall to the level of your systems.", by: "詹姆斯·克利爾 James Clear", ig: "jamesclear" },
  { zh: "每天都努力讓自己比早上起床時，聰明一點點。", en: "Spend each day trying to be a little wiser than you were when you woke up.", by: "查理·蒙格 Charlie Munger" },
  { zh: "你能做的最好的投資，就是投資自己。", en: "The best investment you can make is in yourself.", by: "華倫·巴菲特 Warren Buffett" },
  { zh: "做出大家想要的東西。", en: "Make something people want.", by: "保羅·格雷厄姆 Paul Graham" },
  { zh: "不要幫產品找客人，要幫客人找產品。", en: "Don't find customers for your products. Find products for your customers.", by: "賽斯·高汀 Seth Godin" },
  { zh: "不是你掌控這一天，就是這一天掌控你。", en: "Either you run the day or the day runs you.", by: "吉姆·羅恩 Jim Rohn" },
  { zh: "一個人的人生成不成功，常常看他敢不敢做那些讓人不自在的對話。", en: "A person's success in life can usually be measured by the number of uncomfortable conversations he or she is willing to have.", by: "提摩西·費里斯 Tim Ferriss", ig: "timferriss" },
  { zh: "障礙，就是路本身。", en: "The obstacle is the way.", by: "萊恩·霍利得 Ryan Holiday" },
  { zh: "示弱不是軟弱。", en: "Vulnerability is not weakness.", by: "布芮尼·布朗 Brené Brown", ig: "brenebrown" },
  { zh: "當我們沒辦法改變情況，就得改變自己。", en: "When we are no longer able to change a situation, we are challenged to change ourselves.", by: "維克多·弗蘭克 Viktor Frankl" },
  { zh: "能做多好就做多好，等你懂得更多了，就做得更好。", en: "Do the best you can until you know better. Then when you know better, do better.", by: "瑪雅·安傑洛 Maya Angelou" },
  { zh: "你得去做那件你覺得自己做不到的事。", en: "You must do the thing you think you cannot do.", by: "艾蓮娜·羅斯福 Eleanor Roosevelt" },
  { zh: "你的時間有限，別浪費在過別人的人生。", en: "Your time is limited, so don't waste it living someone else's life.", by: "史蒂夫·賈伯斯 Steve Jobs" },
  { zh: "保持飢渴，保持傻氣。", en: "Stay hungry. Stay foolish.", by: "史蒂夫·賈伯斯 Steve Jobs" },
  { zh: "如果你每年做的實驗多一倍，你的創新也會多一倍。", en: "If you double the number of experiments you do per year, you're going to double your inventiveness.", by: "傑夫·貝佐斯 Jeff Bezos" },
  { zh: "想像力比知識更重要。", en: "Imagination is more important than knowledge.", by: "愛因斯坦 Albert Einstein" },
  { zh: "人生就像騎腳踏車，想不跌倒，就要一直往前騎。", en: "Life is like riding a bicycle. To keep your balance, you must keep moving.", by: "愛因斯坦 Albert Einstein" },
  { zh: "最重要的是，不要停止發問。", en: "The important thing is not to stop questioning.", by: "愛因斯坦 Albert Einstein" },
  { zh: "絕對不要放棄，絕對、絕對、絕對不要放棄。", en: "Never give in—never, never, never, never.", by: "溫斯頓·邱吉爾 Winston Churchill" },
  { zh: "我們唯一該怕的，就是害怕本身。", en: "The only thing we have to fear is fear itself.", by: "富蘭克林·羅斯福 Franklin D. Roosevelt" },
  { zh: "在做完之前，每件事看起來都不可能。", en: "It always seems impossible until it's done.", by: "納爾遜·曼德拉 Nelson Mandela" },
  { zh: "教育是你能用來改變世界最有力的武器。", en: "Education is the most powerful weapon which you can use to change the world.", by: "納爾遜·曼德拉 Nelson Mandela" },
  { zh: "黑暗趕不走黑暗，只有光可以；仇恨趕不走仇恨，只有愛可以。", en: "Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.", by: "馬丁·路德·金恩 Martin Luther King Jr." },
  { zh: "最大的錯覺，就是以為外面有某個東西，只要得到它，我就能永遠快樂、滿足。", en: "The fundamental delusion: there is something out there that will make me happy and fulfilled forever once I have it.", by: "納瓦爾·拉維坎特 Naval Ravikant" },
  { zh: "靠出租自己的時間，是不可能變有錢的。", en: "You're not going to get rich renting out your time.", by: "納瓦爾·拉維坎特 Naval Ravikant" },
  { zh: "如果你沒辦法決定，答案就是不要。", en: "If you can't decide, the answer is no.", by: "納瓦爾·拉維坎特 Naval Ravikant" },
  { zh: "讀比聽快，做比看快。", en: "Reading is faster than listening. Doing is faster than watching.", by: "納瓦爾·拉維坎特 Naval Ravikant" },
  { zh: "用專屬知識、負責任的態度和槓桿，把自己武裝起來。", en: "Arm yourself with specific knowledge, accountability, and leverage.", by: "納瓦爾·拉維坎特 Naval Ravikant" },
  { zh: "快樂是你做的選擇，也是你可以練出來的能力。", en: "Happiness is a choice you make and a skill you develop.", by: "納瓦爾·拉維坎特 Naval Ravikant" },
  { zh: "未來的工作不會再是工作，而是玩。", en: "The future of work will not be work. It will be play.", by: "丹·寇 Dan Koe", ig: "thedankoe" },
  { zh: "專注，讓你分得出行動和分心、有意義和沒意義，也分得出成功和失敗。", en: "Focus is what separates action from distraction, meaning from meaningless, and success from failure.", by: "丹·寇 Dan Koe", ig: "thedankoe" },
  { zh: "生產力有個矛盾：你工作得越少，作品反而越好。", en: "The paradox of productivity is the less you work, the higher quality your work is.", by: "丹·寇 Dan Koe", ig: "thedankoe" },
  { zh: "一個人的體力沒辦法放大，但他腦袋裡的創意可以。", en: "One man's labor cannot scale, but the creative ability of his mind can.", by: "丹·寇 Dan Koe", ig: "thedankoe" },
  { zh: "未來要我們用腦袋賺錢，不是用時間。", en: "The future demands that we earn with our mind, not our time.", by: "丹·寇 Dan Koe", ig: "thedankoe" },
  { zh: "我真正的人生目標，是走的時候，已經沒有東西可以再給了。", en: "My real-life goal is to die with nothing left to give.", by: "亞歷克斯·霍爾莫齊 Alex Hormozi", ig: "hormozi" },
  { zh: "做得夠多，運氣就不重要了。", en: "Volume negates luck.", by: "亞歷克斯·霍爾莫齊 Alex Hormozi", ig: "hormozi" },
  { zh: "你做的每一個行動，都是在替你想成為的那種人投一票。", en: "Every action you take is a vote for the type of person you wish to become.", by: "詹姆斯·克利爾 James Clear", ig: "jamesclear" },
  { zh: "你該在意的是現在的方向，不是現在的成績。", en: "You should be far more concerned with your current trajectory than your current results.", by: "詹姆斯·克利爾 James Clear", ig: "jamesclear" },
  { zh: "習慣，就是自我成長的複利。", en: "Habits are the compound interest of self-improvement.", by: "詹姆斯·克利爾 James Clear", ig: "jamesclear" },
  { zh: "目標用來決定方向，系統才能讓你真的往前走。", en: "Goals are good for setting a direction, but systems are best for making progress.", by: "詹姆斯·克利爾 James Clear", ig: "jamesclear" },
  { zh: "想改變自己是誰，最實在的方法，就是改變自己做的事。", en: "The most practical way to change who you are is to change what you do.", by: "詹姆斯·克利爾 James Clear", ig: "jamesclear" },
  { zh: "倒過來想，永遠倒過來想。", en: "Invert, always invert.", by: "查理·蒙格 Charlie Munger" },
  { zh: "真正賺大錢的，不是買進或賣出，而是等待。", en: "The big money is not in the buying or the selling, but in the waiting.", by: "查理·蒙格 Charlie Munger" },
  { zh: "找一個簡單的想法，然後認真去做。", en: "Take a simple idea and take it seriously.", by: "查理·蒙格 Charlie Munger" },
  { zh: "今天有人能在樹蔭下乘涼，是因為很久以前有人種了一棵樹。", en: "Someone's sitting in the shade today because someone planted a tree a long time ago.", by: "華倫·巴菲特 Warren Buffett" },
  { zh: "風險來自於你不知道自己在做什麼。", en: "Risk comes from not knowing what you're doing.", by: "華倫·巴菲特 Warren Buffett" },
  { zh: "建立名聲要二十年，毀掉只要五分鐘。", en: "It takes 20 years to build a reputation and five minutes to ruin it.", by: "華倫·巴菲特 Warren Buffett" },
  { zh: "活在未來，然後把還缺的東西做出來。", en: "Live in the future, then build what's missing.", by: "保羅·格雷厄姆 Paul Graham" },
  { zh: "想出創業點子的方法，就是不要硬去想創業點子。", en: "The way to get startup ideas is not to try to think of startup ideas.", by: "保羅·格雷厄姆 Paul Graham" },
  { zh: "如果答案是更多資訊，那我們早就都是有完美腹肌的億萬富翁了。", en: "If more information was the answer, then we'd all be billionaires with perfect abs.", by: "德瑞克·西弗斯 Derek Sivers" },
  { zh: "如果你對一件事的反應不是「太棒了，就是它！」，那就說不要。", en: "If you're not saying 'HELL YEAH!' about something, say 'no.'", by: "德瑞克·西弗斯 Derek Sivers" },
  { zh: "理財好不好，跟你多聰明沒什麼關係，主要看你的行為。", en: "Doing well with money has a little to do with how smart you are and a lot to do with how you behave.", by: "莫根·豪瑟爾 Morgan Housel" },
  { zh: "花錢給人看你有多少錢，是讓你錢變少最快的方法。", en: "Spending money to show people how much money you have is the fastest way to have less money.", by: "莫根·豪瑟爾 Morgan Housel" },
  { zh: "存錢，就是你的面子和你的收入之間的差距。", en: "Saving is the gap between your ego and your income.", by: "莫根·豪瑟爾 Morgan Housel" },
  { zh: "人不是因為你做了什麼才買，而是因為你為什麼這樣做。", en: "People don't buy what you do; they buy why you do it.", by: "賽門·西奈克 Simon Sinek", ig: "simonsinek" },
  { zh: "夢想要大，從小處開始，但最重要的是，開始。", en: "Dream big. Start small. But most of all, start.", by: "賽門·西奈克 Simon Sinek", ig: "simonsinek" },
  { zh: "說清楚是善意，說不清楚就是不體貼。", en: "Clear is kind. Unclear is unkind.", by: "布芮尼·布朗 Brené Brown", ig: "brenebrown" },
  { zh: "你可以選勇氣，也可以選舒服，但兩個不能都要。", en: "You can choose courage or you can choose comfort, but you cannot choose both.", by: "布芮尼·布朗 Brené Brown", ig: "brenebrown" },
  { zh: "紀律就是自由。", en: "Discipline equals freedom.", by: "喬科·威林克 Jocko Willink", ig: "jockowillink" },
  { zh: "別指望有動力，要靠紀律。", en: "Don't count on motivation. Count on discipline.", by: "喬科·威林克 Jocko Willink", ig: "jockowillink" },
  { zh: "你正處在一個危險裡：日子過得太舒服、太安逸，到死都沒發現自己真正的潛力。", en: "You are in danger of living a life so comfortable and soft, that you will die without ever realizing your true potential.", by: "大衛·高金斯 David Goggins", ig: "davidgoggins" },
  { zh: "我們最怕做的事，往往就是最該做的事。", en: "What we fear doing most is usually what we most need to do.", by: "提摩西·費里斯 Tim Ferriss", ig: "timferriss" },
  { zh: "忙是一種懶：懶得思考，只是亂做一通。", en: "Being busy is a form of laziness—lazy thinking and indiscriminate action.", by: "提摩西·費里斯 Tim Ferriss", ig: "timferriss" },
  { zh: "創新，是領導者和跟隨者的差別。", en: "Innovation distinguishes between a leader and a follower.", by: "史蒂夫·賈伯斯 Steve Jobs" },
  { zh: "簡單，往往比複雜更難。", en: "Simple can be harder than complex.", by: "史蒂夫·賈伯斯 Steve Jobs" },
  { zh: "吸收有用的，丟掉沒用的，再加上屬於你自己的。", en: "Absorb what is useful, discard what is not, add what is uniquely your own.", by: "李小龍 Bruce Lee" },
  { zh: "我這輩子失敗了一次又一次，這就是我成功的原因。", en: "I've failed over and over and over again in my life. And that is why I succeed.", by: "麥可·喬丹 Michael Jordan" },
  { zh: "我可以接受失敗，每個人都會在某些事上失敗。但我不能接受自己沒有試過。", en: "I can accept failure, everyone fails at something. But I can't accept not trying.", by: "麥可·喬丹 Michael Jordan" },
  { zh: "最重要的是去鼓舞別人，讓他們在自己想做的事上做到最好。", en: "The most important thing is to try and inspire people so that they can be great in whatever they want to do.", by: "柯比·布萊恩 Kobe Bryant" },
  { zh: "現在先吃苦，然後用下半輩子當冠軍。", en: "Suffer now and live the rest of your life as a champion.", by: "穆罕默德·阿里 Muhammad Ali" },
  { zh: "我知道就算失敗了我也不會後悔，唯一可能後悔的，是從來沒試過。", en: "I knew that if I failed I wouldn't regret that, but I knew the one thing I might regret is not ever trying.", by: "傑夫·貝佐斯 Jeff Bezos" },
  { zh: "當一件事夠重要，就算機率不站在你這邊，你還是會去做。", en: "When something is important enough, you do it even if the odds are not in your favor.", by: "伊隆·馬斯克 Elon Musk" },
  { zh: "把你的傷痛，變成智慧。", en: "Turn your wounds into wisdom.", by: "歐普拉·溫芙蕾 Oprah Winfrey" },
  { zh: "我學到，勇氣不是不害怕，而是戰勝害怕。", en: "I learned that courage was not the absence of fear, but the triumph over it.", by: "納爾遜·曼德拉 Nelson Mandela" },
  { zh: "你可能會遇到很多次失敗，但你不能被打倒。", en: "You may encounter many defeats, but you must not be defeated.", by: "瑪雅·安傑洛 Maya Angelou" },
  { zh: "有「為什麼」要活下去的人，幾乎什麼樣的「怎麼活」都撐得過去。", en: "Those who have a 'why' to live, can bear with almost any 'how'.", by: "維克多·弗蘭克 Viktor Frankl" },
  { zh: "一個人什麼都可以被奪走，只有一樣不行：不管處境多糟，都能選擇自己的態度，這是人最後的自由。", en: "Everything can be taken from a man but one thing: the last of the human freedoms—to choose one's attitude in any given set of circumstances.", by: "維克多·弗蘭克 Viktor Frankl" },
  { zh: "要進步就要改變；要完美，就要常常改變。", en: "To improve is to change; to be perfect is to change often.", by: "溫斯頓·邱吉爾 Winston Churchill" },
  { zh: "如果我們用自己的初衷，而不是成就來定義自己，人生會更有意義。", en: "Life is more meaningful when we define ourselves by our intentions rather than our achievements.", by: "傑·謝提 Jay Shetty", ig: "jayshetty" },
  { zh: "草會比較綠，是因為你有在那裡澆水。", en: "The grass is greener where you water it.", by: "傑·謝提 Jay Shetty", ig: "jayshetty" },
  { zh: "活在當下，是過上豐富圓滿人生的唯一方法。", en: "Being present is the only way to live a truly rich and full life.", by: "傑·謝提 Jay Shetty", ig: "jayshetty" },
  { zh: "放下，讓我們自由，而自由是快樂的唯一條件。", en: "Letting go gives us freedom, and freedom is the only condition for happiness.", by: "傑·謝提 Jay Shetty", ig: "jayshetty" },
  { zh: "點子不值錢，執行才是重點。", en: "Ideas are shit, execution is the game.", by: "蓋瑞·范納洽 Gary Vaynerchuk", ig: "garyvee" },
  { zh: "記錄就好，不要刻意創作。", en: "Document, don't create.", by: "蓋瑞·范納洽 Gary Vaynerchuk", ig: "garyvee" },
  { zh: "一有想為目標行動的念頭，就倒數 5、4、3、2、1，馬上動起來，不然你的大腦會把它擋下來。", en: "The moment you have an instinct to act on a goal you must 5-4-3-2-1 and physically move or your brain will stop you.", by: "梅爾·羅賓斯 Mel Robbins", ig: "melrobbins" },
  { zh: "別再等動力了，那只是個迷思。", en: "Forget motivation; it's a myth.", by: "梅爾·羅賓斯 Mel Robbins", ig: "melrobbins" },
  { zh: "問對問題，人生就會更好。", en: "Quality questions create a quality life.", by: "東尼·羅賓斯 Tony Robbins", ig: "tonyrobbins" },
  { zh: "決定我們人生的，不是偶爾做的事，而是一直在做的事。", en: "It's not what we do once in a while that shapes our lives, but what we do consistently.", by: "東尼·羅賓斯 Tony Robbins", ig: "tonyrobbins" },
  { zh: "如果你想成功，想得就像想呼吸一樣，你就會成功。", en: "When you want to succeed as bad as you want to breathe, then you'll be successful.", by: "艾瑞克·湯瑪斯 Eric Thomas", ig: "etthehiphoppreacher" },
  { zh: "改變，一開始最難，中間最亂，最後最棒。", en: "Change is hardest at the beginning, messiest in the middle and best at the end.", by: "羅賓·夏瑪 Robin Sharma", ig: "robinsharma" },
];
