// 每日佳句資料庫。句子數量 = 循環週期(天)。新增句子只需在陣列末尾加一行。
// zh: 中文  en: English  by: 作者 / Author
window.QUOTES = [
  { zh: "天行健，君子以自強不息。", en: "As heaven moves vigorously, the gentleman strives tirelessly to improve himself.", by: "《易經》 I Ching" },
  { zh: "千里之行，始於足下。", en: "A journey of a thousand miles begins with a single step.", by: "老子 Laozi" },
  { zh: "知人者智，自知者明。", en: "To know others is intelligence; to know yourself is true wisdom.", by: "老子 Laozi" },
  { zh: "學而不思則罔，思而不學則殆。", en: "Learning without thought is labor lost; thought without learning is perilous.", by: "孔子 Confucius" },
  { zh: "三人行，必有我師焉。", en: "When walking with two others, I will surely find a teacher among them.", by: "孔子 Confucius" },
  { zh: "不患人之不己知，患不知人也。", en: "Do not worry that others do not know you; worry that you do not know others.", by: "孔子 Confucius" },
  { zh: "己所不欲，勿施於人。", en: "Do not impose on others what you yourself do not desire.", by: "孔子 Confucius" },
  { zh: "知之者不如好之者，好之者不如樂之者。", en: "Those who know it are not equal to those who love it; those who love it are not equal to those who delight in it.", by: "孔子 Confucius" },
  { zh: "人無遠慮，必有近憂。", en: "He who gives no thought to what is distant will find sorrow near at hand.", by: "孔子 Confucius" },
  { zh: "君子坦蕩蕩，小人長戚戚。", en: "The noble person is calm and at ease; the petty person is always full of worry.", by: "孔子 Confucius" },
  { zh: "勝人者有力，自勝者強。", en: "Mastering others is strength; mastering yourself is true power.", by: "老子 Laozi" },
  { zh: "上善若水。", en: "The highest good is like water.", by: "老子 Laozi" },
  { zh: "合抱之木，生於毫末；九層之臺，起於累土。", en: "A tree that fills a man's embrace grows from a tiny sprout; a nine-story tower rises from a heap of earth.", by: "老子 Laozi" },
  { zh: "天生我材必有用。", en: "Heaven gave me talent; it must be of use.", by: "李白 Li Bai" },
  { zh: "長風破浪會有時，直掛雲帆濟滄海。", en: "A time will come to ride the wind and break the waves; I will hoist my cloud-white sail and cross the sea.", by: "李白 Li Bai" },
  { zh: "會當凌絕頂，一覽眾山小。", en: "Once I stand atop the highest peak, all the mountains below will look small.", by: "杜甫 Du Fu" },
  { zh: "海內存知己，天涯若比鄰。", en: "With a true friend within the seas, even the far horizon feels like a neighbor.", by: "王勃 Wang Bo" },
  { zh: "欲窮千里目，更上一層樓。", en: "To see a thousand miles further, climb one more story.", by: "王之渙 Wang Zhihuan" },
  { zh: "莫等閒，白了少年頭，空悲切。", en: "Do not idle away your youth until your hair turns white and regret is all that remains.", by: "岳飛 Yue Fei" },
  { zh: "先天下之憂而憂，後天下之樂而樂。", en: "Be the first to worry about the world's troubles, the last to enjoy its pleasures.", by: "范仲淹 Fan Zhongyan" },
  { zh: "山重水複疑無路，柳暗花明又一村。", en: "Where hills and streams seem to end, willows and flowers bloom—and another village appears.", by: "陸游 Lu You" },
  { zh: "紙上得來終覺淺，絕知此事要躬行。", en: "Knowledge from paper is always shallow; to truly understand, you must practice it yourself.", by: "陸游 Lu You" },
  { zh: "問渠那得清如許？為有源頭活水來。", en: "How can the pond be so clear? Because fresh water keeps flowing in from its source.", by: "朱熹 Zhu Xi" },
  { zh: "少壯不努力，老大徒傷悲。", en: "If you do not strive in youth, you will only grieve in old age.", by: "《長歌行》 Ballad of Long Songs" },
  { zh: "寶劍鋒從磨礪出，梅花香自苦寒來。", en: "A sword's edge comes from grinding; the plum blossom's fragrance comes from bitter cold.", by: "古諺 Chinese proverb" },
  { zh: "一寸光陰一寸金，寸金難買寸光陰。", en: "An inch of time is an inch of gold, but an inch of gold cannot buy back an inch of time.", by: "古諺 Chinese proverb" },
  { zh: "世上無難事，只怕有心人。", en: "Nothing in the world is difficult for one who sets their mind to it.", by: "古諺 Chinese proverb" },
  { zh: "失敗是成功之母。", en: "Failure is the mother of success.", by: "古諺 Chinese proverb" },
  { zh: "有志者，事竟成。", en: "Where there is a will, there is a way.", by: "《後漢書》 Book of the Later Han" },
  { zh: "你無法回到過去重新開始，但可以從現在開始，創造全新的結局。", en: "You can't go back and change the beginning, but you can start where you are and change the ending.", by: "C.S. 路易斯 C.S. Lewis" },
  { zh: "我們反覆做的事情造就了我們。因此，卓越不是一種行為，而是一種習慣。", en: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", by: "威爾·杜蘭特 Will Durant" },
  { zh: "未經審視的人生不值得過。", en: "The unexamined life is not worth living.", by: "蘇格拉底 Socrates" },
  { zh: "我知道我一無所知。", en: "I know that I know nothing.", by: "蘇格拉底 Socrates" },
  { zh: "幸福取決於我們自己。", en: "Happiness depends upon ourselves.", by: "亞里斯多德 Aristotle" },
  { zh: "我思，故我在。", en: "I think, therefore I am.", by: "笛卡兒 René Descartes" },
  { zh: "決定我們命運的，不是發生了什麼，而是我們如何回應。", en: "It's not what happens to you, but how you react to it that matters.", by: "愛比克泰德 Epictetus" },
  { zh: "你的心靈會染上你反覆思考的顏色。", en: "The soul becomes dyed with the color of its thoughts.", by: "馬可·奧理略 Marcus Aurelius" },
  { zh: "阻礙行動的，反而推動行動；擋在路上的，反而成為道路。", en: "The impediment to action advances action. What stands in the way becomes the way.", by: "馬可·奧理略 Marcus Aurelius" },
  { zh: "我們受的苦，往往多於我們遭遇的事。", en: "We suffer more often in imagination than in reality.", by: "塞內卡 Seneca" },
  { zh: "人生並不短暫，是我們浪費了太多時間。", en: "It is not that we have a short time to live, but that we waste much of it.", by: "塞內卡 Seneca" },
  { zh: "想像力比知識更重要。", en: "Imagination is more important than knowledge.", by: "愛因斯坦 Albert Einstein" },
  { zh: "生活就像騎單車，想保持平衡就得不斷前進。", en: "Life is like riding a bicycle. To keep your balance, you must keep moving.", by: "愛因斯坦 Albert Einstein" },
  { zh: "重要的是不要停止提問。", en: "The important thing is not to stop questioning.", by: "愛因斯坦 Albert Einstein" },
  { zh: "人生中沒有什麼可怕的，只有需要被理解的。", en: "Nothing in life is to be feared, it is only to be understood.", by: "瑪麗·居禮 Marie Curie" },
  { zh: "我沒有失敗，我只是找到了一萬種行不通的方法。", en: "I have not failed. I've just found 10,000 ways that won't work.", by: "愛迪生 Thomas Edison" },
  { zh: "預測未來的最好方法，就是去創造它。", en: "The best way to predict the future is to create it.", by: "彼得·杜拉克 Peter Drucker" },
  { zh: "求知若飢，虛心若愚。", en: "Stay hungry. Stay foolish.", by: "史蒂夫·賈伯斯 Steve Jobs" },
  { zh: "做偉大的工作，唯一的方法就是熱愛你所做的事。", en: "The only way to do great work is to love what you do.", by: "史蒂夫·賈伯斯 Steve Jobs" },
  { zh: "在事情完成之前，一切看起來都像不可能。", en: "It always seems impossible until it's done.", by: "納爾遜·曼德拉 Nelson Mandela" },
  { zh: "教育是你能用來改變世界最強大的武器。", en: "Education is the most powerful weapon which you can use to change the world.", by: "納爾遜·曼德拉 Nelson Mandela" },
  { zh: "黑暗無法驅逐黑暗，只有光明可以；仇恨無法驅逐仇恨，只有愛可以。", en: "Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.", by: "馬丁·路德·金恩 Martin Luther King Jr." },
  { zh: "你不需要看到整個樓梯，只要踏出第一步。", en: "You don't have to see the whole staircase, just take the first step.", by: "馬丁·路德·金恩 Martin Luther King Jr." },
  { zh: "我們最深的恐懼，不是自己不夠好，而是自己的力量超乎想像。", en: "Our deepest fear is not that we are inadequate. Our deepest fear is that we are powerful beyond measure.", by: "瑪麗安·威廉森 Marianne Williamson" },
  { zh: "凡事豫則立，不豫則廢。", en: "Preparation leads to success; without it, there is failure.", by: "《中庸》 Doctrine of the Mean" },
  { zh: "靜以修身，儉以養德。", en: "Cultivate yourself through stillness; nurture virtue through frugality.", by: "諸葛亮 Zhuge Liang" },
  { zh: "非淡泊無以明志，非寧靜無以致遠。", en: "Without simplicity there is no clarity of purpose; without tranquility there is no reaching far.", by: "諸葛亮 Zhuge Liang" },
  { zh: "操千曲而後曉聲，觀千劍而後識器。", en: "Play a thousand tunes and you will know music; examine a thousand swords and you will know blades.", by: "劉勰 Liu Xie" },
  { zh: "路漫漫其修遠兮，吾將上下而求索。", en: "The road is long and far; I will search high and low.", by: "屈原 Qu Yuan" },
  { zh: "海納百川，有容乃大。", en: "The sea accepts a hundred rivers; tolerance makes it great.", by: "林則徐 Lin Zexu" },
  { zh: "苟日新，日日新，又日新。", en: "If you can renew yourself one day, do so every day, and again each day.", by: "《大學》 The Great Learning" },
  { zh: "不積跬步，無以至千里；不積小流，無以成江海。", en: "Without accumulating small steps, you cannot go a thousand miles; without small streams, there are no rivers and seas.", by: "荀子 Xunzi" },
  { zh: "天下難事，必作於易；天下大事，必作於細。", en: "The hardest things in the world begin with the easy; the greatest begin with the small.", by: "老子 Laozi" },
  { zh: "生於憂患，死於安樂。", en: "We thrive in adversity and perish in comfort.", by: "孟子 Mencius" },
  { zh: "吾生也有涯，而知也無涯。", en: "Our life has limits, but knowledge has none.", by: "莊子 Zhuangzi" },
  { zh: "魚，我所欲也；熊掌，亦我所欲也。二者不可得兼，舍魚而取熊掌者也。", en: "I want fish, and I want bear's paw; if I cannot have both, I will give up the fish for the bear's paw.", by: "孟子 Mencius" },
  { zh: "你今天的努力，是明天的底氣。", en: "Today's effort is tomorrow's confidence.", by: "現代諺語 Modern saying" },
  { zh: "語言有力量：你對自己說的話，會慢慢成為你。", en: "Words have power: what you tell yourself, you slowly become.", by: "每日佳句 Daily Quotes" },
  { zh: "永不放棄，永不、永不、永不放棄。", en: "Never give in—never, never, never, never.", by: "溫斯頓·邱吉爾 Winston Churchill" },
  { zh: "我們唯一需要恐懼的，就是恐懼本身。", en: "The only thing we have to fear is fear itself.", by: "富蘭克林·羅斯福 Franklin D. Roosevelt" },
  { zh: "勇氣是對恐懼的抵抗、對恐懼的掌控，而不是沒有恐懼。", en: "Courage is resistance to fear, mastery of fear—not absence of fear.", by: "馬克·吐溫 Mark Twain" },
];
