// 每日佳句資料庫(近百年的現代名人)。句子數量 = 循環週期(天)。新增只需在陣列末尾加一行。
// zh: 中文(翻譯)  en: 英文原句  by: 「中文名 English name」
window.QUOTES = [
  // —— Naval Ravikant ——
  { zh: "要追求財富，而不是金錢或地位。財富，是那些在你睡覺時也能替你賺錢的資產。", en: "Seek wealth, not money or status. Wealth is having assets that earn while you sleep.", by: "納瓦爾·拉維坎特 Naval Ravikant" },
  { zh: "學會銷售，也學會打造。兩者都會，你就無人能擋。", en: "Learn to sell. Learn to build. If you can do both, you will be unstoppable.", by: "納瓦爾·拉維坎特 Naval Ravikant" },
  { zh: "專屬知識，是無法靠培訓學會的知識。", en: "Specific knowledge is knowledge you cannot be trained for.", by: "納瓦爾·拉維坎特 Naval Ravikant" },
  { zh: "選一個行業，和願意長期合作的人，玩一場長期的遊戲。", en: "Pick an industry where you can play long-term games with long-term people.", by: "納瓦爾·拉維坎特 Naval Ravikant" },
  { zh: "慾望，是你和自己簽下的契約：在得到想要的東西之前，你註定不快樂。", en: "Desire is a contract you make with yourself to be unhappy until you get what you want.", by: "納瓦爾·拉維坎特 Naval Ravikant" },
  { zh: "用腦袋賺錢，而不是用時間換錢。", en: "Earn with your mind, not your time.", by: "納瓦爾·拉維坎特 Naval Ravikant" },
  { zh: "讀你喜歡的書，一直讀到你愛上閱讀為止。", en: "Read what you love until you love to read.", by: "納瓦爾·拉維坎特 Naval Ravikant" },
  { zh: "靈感稍縱即逝，有了就立刻行動。", en: "Inspiration is perishable—act on it immediately.", by: "納瓦爾·拉維坎特 Naval Ravikant" },
  { zh: "想擺脫競爭，就做真實的自己。", en: "Escape competition through authenticity.", by: "納瓦爾·拉維坎特 Naval Ravikant" },
  { zh: "一顆平靜的心、一副健康的身體、一個充滿愛的家。這些用錢買不到，只能靠自己去爭取。", en: "A calm mind, a fit body, a house full of love. These things cannot be bought. They must be earned.", by: "納瓦爾·拉維坎特 Naval Ravikant" },
  { zh: "程式碼和媒體，是不需要任何人批准的槓桿。", en: "Code and media are permissionless leverage.", by: "納瓦爾·拉維坎特 Naval Ravikant" },
  { zh: "別理會那些玩地位遊戲的人。他們靠攻擊創造財富的人，來換取自己的地位。", en: "Ignore people playing status games. They gain status by attacking people playing wealth creation games.", by: "納瓦爾·拉維坎特 Naval Ravikant" },

  // —— Dan Koe ——
  { zh: "如果你不選擇自己的奮鬥，生活就會替你指派一個。", en: "If you don't choose a struggle, you will be assigned one.", by: "丹·寇 Dan Koe" },
  { zh: "如果你不知道自己要什麼，別人就會告訴你該要什麼，而你還會信以為真。", en: "If you don't know what you want, you will be told what you want, and you will believe it.", by: "丹·寇 Dan Koe" },
  { zh: "如果你不替自己訂下人生目標，就會被指派一個。", en: "If you don't create a purpose, you will be assigned one.", by: "丹·寇 Dan Koe" },
  { zh: "勉強自己踏進不舒服的處境，才不會活到五十歲，心智成熟度卻還停在十五歲。", en: "Force yourself into uncomfortable situations so you don't end up being 50 years old with the emotional maturity of a 15 year old.", by: "丹·寇 Dan Koe" },
  { zh: "世上沒有比「看看自己究竟能做到什麼」更值得投入一生的事。", en: "There doesn't seem to be a more worthwhile endeavor to dedicate your life to than to see what you are capable of.", by: "丹·寇 Dan Koe" },
  { zh: "沒有什麼比你的潛力更重要：不是手機，不是電視，也不是任何此刻正勾著你大腦獎勵機制的東西。", en: "Nothing is more important than your potential. Not your phone, not the TV, not anything that is begging to stimulate your brain's reward system right now.", by: "丹·寇 Dan Koe" },
  { zh: "光是想，永遠解決不了必須靠動手才能解決的問題。", en: "No amount of thinking is going to fix the problem that is solved by doing.", by: "丹·寇 Dan Koe" },
  { zh: "比追求最好的自己更困難的，就是不去追求最好的自己。", en: "The only thing more challenging than pursuing the highest version of yourself is not pursuing the highest version of yourself.", by: "丹·寇 Dan Koe" },

  // —— Alex Hormozi ——
  { zh: "提出一個好到讓人拒絕了會覺得自己很笨的方案。", en: "Make people an offer so good they would feel stupid saying no.", by: "亞歷克斯·霍爾莫齊 Alex Hormozi" },
  { zh: "價格是你付出的，價值是你得到的。", en: "Price is what you pay. Value is what you get.", by: "亞歷克斯·霍爾莫齊 Alex Hormozi" },
  { zh: "痛點，就是你的賣點。", en: "The pain is the pitch.", by: "亞歷克斯·霍爾莫齊 Alex Hormozi" },
  { zh: "人們對失去的恐懼，比對得到的渴望更強烈。", en: "Fear of loss is stronger than desire for gain.", by: "亞歷克斯·霍爾莫齊 Alex Hormozi" },
  { zh: "提供最多價值的企業，就是贏家。沒有例外。", en: "The business that provides the most value wins. Period.", by: "亞歷克斯·霍爾莫齊 Alex Hormozi" },
  { zh: "不求回報地幫助別人，會讓人更有成就感、更長壽，也賺得更多。", en: "People who help others (with zero expectation) experience higher levels of fulfillment, live longer, and make more money.", by: "亞歷克斯·霍爾莫齊 Alex Hormozi" },
  { zh: "開始經營內容的最好時機是你出生那天，第二好的時機就是現在。", en: "The best day to start posting content was the day you were born. The second best day is today.", by: "亞歷克斯·霍爾莫齊 Alex Hormozi" },
  { zh: "別在意別人怎麼想。如果某個人不會出席你的葬禮致詞，你活著的時候就不必在乎他的看法。", en: "Don't be afraid of what other people think. If someone won't speak at your funeral, you shouldn't care about their opinion while you're alive.", by: "亞歷克斯·霍爾莫齊 Alex Hormozi" },

  // —— 其他現代作者與創業家 ——
  { zh: "你不會升到目標的高度，只會掉回系統的水準。", en: "You do not rise to the level of your goals. You fall to the level of your systems.", by: "詹姆斯·克利爾 James Clear" },
  { zh: "每天都努力讓自己比早上醒來時，更有智慧一點。", en: "Spend each day trying to be a little wiser than you were when you woke up.", by: "查理·蒙格 Charlie Munger" },
  { zh: "你能做的最好投資，就是投資自己。", en: "The best investment you can make is in yourself.", by: "華倫·巴菲特 Warren Buffett" },
  { zh: "做出大家想要的東西。", en: "Make something people want.", by: "保羅·格雷厄姆 Paul Graham" },
  { zh: "別替產品找客戶，要替客戶找產品。", en: "Don't find customers for your products. Find products for your customers.", by: "賽斯·高汀 Seth Godin" },
  { zh: "要嘛你掌控這一天，要嘛這一天掌控你。", en: "Either you run the day or the day runs you.", by: "吉姆·羅恩 Jim Rohn" },
  { zh: "一個人人生的成就，往往可以用他願意進行的不舒服對話有多少來衡量。", en: "A person's success in life can usually be measured by the number of uncomfortable conversations he or she is willing to have.", by: "提摩西·費里斯 Tim Ferriss" },
  { zh: "障礙，就是道路。", en: "The obstacle is the way.", by: "萊恩·霍利得 Ryan Holiday" },
  { zh: "示弱並不是軟弱。", en: "Vulnerability is not weakness.", by: "布芮尼·布朗 Brené Brown" },
  { zh: "當我們無法改變處境時，就得面對改變自己的挑戰。", en: "When we are no longer able to change a situation, we are challenged to change ourselves.", by: "維克多·弗蘭克 Viktor Frankl" },
  { zh: "盡你所能，直到你懂得更多；懂得更多之後，就做得更好。", en: "Do the best you can until you know better. Then when you know better, do better.", by: "瑪雅·安傑洛 Maya Angelou" },
  { zh: "你必須去做那件你認為自己做不到的事。", en: "You must do the thing you think you cannot do.", by: "艾蓮娜·羅斯福 Eleanor Roosevelt" },
  { zh: "你的時間有限，別浪費在過別人的人生。", en: "Your time is limited, so don't waste it living someone else's life.", by: "史蒂夫·賈伯斯 Steve Jobs" },
  { zh: "求知若飢，虛心若愚。", en: "Stay hungry. Stay foolish.", by: "史蒂夫·賈伯斯 Steve Jobs" },
  { zh: "如果你每年做的實驗次數加倍，你的創新能力也會加倍。", en: "If you double the number of experiments you do per year, you're going to double your inventiveness.", by: "傑夫·貝佐斯 Jeff Bezos" },
  { zh: "想像力比知識更重要。", en: "Imagination is more important than knowledge.", by: "愛因斯坦 Albert Einstein" },
  { zh: "人生就像騎腳踏車，想保持平衡，就得不斷前進。", en: "Life is like riding a bicycle. To keep your balance, you must keep moving.", by: "愛因斯坦 Albert Einstein" },
  { zh: "重要的是，不要停止發問。", en: "The important thing is not to stop questioning.", by: "愛因斯坦 Albert Einstein" },
  { zh: "絕不屈服，絕不、絕不、絕不屈服。", en: "Never give in—never, never, never, never.", by: "溫斯頓·邱吉爾 Winston Churchill" },
  { zh: "我們唯一需要害怕的，就是害怕本身。", en: "The only thing we have to fear is fear itself.", by: "富蘭克林·羅斯福 Franklin D. Roosevelt" },
  { zh: "在事情完成之前，一切看起來都像是不可能。", en: "It always seems impossible until it's done.", by: "納爾遜·曼德拉 Nelson Mandela" },
  { zh: "教育是你能用來改變世界最強大的武器。", en: "Education is the most powerful weapon which you can use to change the world.", by: "納爾遜·曼德拉 Nelson Mandela" },
  { zh: "黑暗無法驅散黑暗，只有光明可以；仇恨無法消除仇恨，只有愛可以。", en: "Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.", by: "馬丁·路德·金恩 Martin Luther King Jr." },
  { zh: "最根本的錯覺，就是以為外面有某樣東西，一旦得到，就能讓我永遠快樂、圓滿。", en: "The fundamental delusion: there is something out there that will make me happy and fulfilled forever once I have it.", by: "納瓦爾·拉維坎特 Naval Ravikant" },
  { zh: "靠出租自己的時間，是不可能致富的。", en: "You're not going to get rich renting out your time.", by: "納瓦爾·拉維坎特 Naval Ravikant" },
  { zh: "如果你無法決定，答案就是不要。", en: "If you can't decide, the answer is no.", by: "納瓦爾·拉維坎特 Naval Ravikant" },
  { zh: "閱讀比聽講快，動手做比看別人做快。", en: "Reading is faster than listening. Doing is faster than watching.", by: "納瓦爾·拉維坎特 Naval Ravikant" },
  { zh: "用專屬知識、承擔責任和槓桿，武裝你自己。", en: "Arm yourself with specific knowledge, accountability, and leverage.", by: "納瓦爾·拉維坎特 Naval Ravikant" },
  { zh: "快樂是一種你做出的選擇，也是一項你可以培養的技能。", en: "Happiness is a choice you make and a skill you develop.", by: "納瓦爾·拉維坎特 Naval Ravikant" },
  { zh: "未來的工作將不再是工作，而是遊戲。", en: "The future of work will not be work. It will be play.", by: "丹·寇 Dan Koe" },
  { zh: "專注，區分了行動與分心、有意義與無意義，也區分了成功與失敗。", en: "Focus is what separates action from distraction, meaning from meaningless, and success from failure.", by: "丹·寇 Dan Koe" },
  { zh: "生產力的矛盾在於：你工作得越少，作品的品質反而越高。", en: "The paradox of productivity is the less you work, the higher quality your work is.", by: "丹·寇 Dan Koe" },
  { zh: "一個人的勞力無法規模化，但他頭腦的創造力可以。", en: "One man's labor cannot scale, but the creative ability of his mind can.", by: "丹·寇 Dan Koe" },
  { zh: "未來要求我們用頭腦賺錢，而不是用時間。", en: "The future demands that we earn with our mind, not our time.", by: "丹·寇 Dan Koe" },
  { zh: "我真正的人生目標，是在離世時，已經沒有任何東西可以再給出去。", en: "My real-life goal is to die with nothing left to give.", by: "亞歷克斯·霍爾莫齊 Alex Hormozi" },
  { zh: "做得夠多，就能抵消運氣的影響。", en: "Volume negates luck.", by: "亞歷克斯·霍爾莫齊 Alex Hormozi" },
  { zh: "你採取的每一個行動，都是在為你想成為的那種人投下一票。", en: "Every action you take is a vote for the type of person you wish to become.", by: "詹姆斯·克利爾 James Clear" },
  { zh: "你該關心的，是目前前進的軌跡，而不是目前的成果。", en: "You should be far more concerned with your current trajectory than your current results.", by: "詹姆斯·克利爾 James Clear" },
  { zh: "習慣，是自我提升的複利。", en: "Habits are the compound interest of self-improvement.", by: "詹姆斯·克利爾 James Clear" },
  { zh: "目標適合用來定方向，系統才最適合用來取得進展。", en: "Goals are good for setting a direction, but systems are best for making progress.", by: "詹姆斯·克利爾 James Clear" },
  { zh: "想改變你是誰，最實際的方法就是改變你做的事。", en: "The most practical way to change who you are is to change what you do.", by: "詹姆斯·克利爾 James Clear" },
  { zh: "反過來想，永遠要反過來想。", en: "Invert, always invert.", by: "查理·蒙格 Charlie Munger" },
  { zh: "真正的大錢，不在買進或賣出，而在等待。", en: "The big money is not in the buying or the selling, but in the waiting.", by: "查理·蒙格 Charlie Munger" },
  { zh: "找一個簡單的想法，然後認真對待它。", en: "Take a simple idea and take it seriously.", by: "查理·蒙格 Charlie Munger" },
  { zh: "今天有人能坐在樹蔭下，是因為很久以前有人種下了一棵樹。", en: "Someone's sitting in the shade today because someone planted a tree a long time ago.", by: "華倫·巴菲特 Warren Buffett" },
  { zh: "風險來自於你不知道自己在做什麼。", en: "Risk comes from not knowing what you're doing.", by: "華倫·巴菲特 Warren Buffett" },
  { zh: "建立名聲要花二十年，毀掉它只要五分鐘。", en: "It takes 20 years to build a reputation and five minutes to ruin it.", by: "華倫·巴菲特 Warren Buffett" },
  { zh: "活在未來，然後把缺少的東西做出來。", en: "Live in the future, then build what's missing.", by: "保羅·格雷厄姆 Paul Graham" },
  { zh: "想到創業點子的方法，不是硬去想創業點子。", en: "The way to get startup ideas is not to try to think of startup ideas.", by: "保羅·格雷厄姆 Paul Graham" },
  { zh: "如果答案是更多資訊，那我們早就都是擁有完美腹肌的億萬富翁了。", en: "If more information was the answer, then we'd all be billionaires with perfect abs.", by: "德瑞克·西弗斯 Derek Sivers" },
  { zh: "如果你對某件事的反應不是「太棒了，就是它！」，那就說不。", en: "If you're not saying 'HELL YEAH!' about something, say 'no.'", by: "德瑞克·西弗斯 Derek Sivers" },
  { zh: "把錢管好，和你有多聰明關係不大，更多取決於你的行為。", en: "Doing well with money has a little to do with how smart you are and a lot to do with how you behave.", by: "莫根·豪瑟爾 Morgan Housel" },
  { zh: "花錢向別人展示你有多少錢，是讓你的錢變少最快的方法。", en: "Spending money to show people how much money you have is the fastest way to have less money.", by: "莫根·豪瑟爾 Morgan Housel" },
  { zh: "儲蓄，就是你的自尊心與收入之間的差距。", en: "Saving is the gap between your ego and your income.", by: "莫根·豪瑟爾 Morgan Housel" },
  { zh: "人們不是因為你做了什麼而買單，而是因為你為什麼這麼做。", en: "People don't buy what you do; they buy why you do it.", by: "賽門·西奈克 Simon Sinek" },
  { zh: "夢想要大，起步要小，但最重要的是，開始行動。", en: "Dream big. Start small. But most of all, start.", by: "賽門·西奈克 Simon Sinek" },
  { zh: "說清楚是一種善意，模糊不清則是不友善。", en: "Clear is kind. Unclear is unkind.", by: "布芮尼·布朗 Brené Brown" },
  { zh: "你可以選擇勇氣，也可以選擇舒適，但無法兩者兼得。", en: "You can choose courage or you can choose comfort, but you cannot choose both.", by: "布芮尼·布朗 Brené Brown" },
  { zh: "紀律等於自由。", en: "Discipline equals freedom.", by: "喬科·威林克 Jocko Willink" },
  { zh: "別指望動力，要靠紀律。", en: "Don't count on motivation. Count on discipline.", by: "喬科·威林克 Jocko Willink" },
  { zh: "你正面臨一種危險：生活過得太舒適、太安逸，以致於到死都沒有發現自己真正的潛力。", en: "You are in danger of living a life so comfortable and soft, that you will die without ever realizing your true potential.", by: "大衛·高金斯 David Goggins" },
  { zh: "我們最害怕做的事，往往正是我們最需要做的事。", en: "What we fear doing most is usually what we most need to do.", by: "提摩西·費里斯 Tim Ferriss" },
  { zh: "忙碌是一種懶惰：懶得思考，只是漫無目的地行動。", en: "Being busy is a form of laziness—lazy thinking and indiscriminate action.", by: "提摩西·費里斯 Tim Ferriss" },
  { zh: "創新，是區分領導者與追隨者的關鍵。", en: "Innovation distinguishes between a leader and a follower.", by: "史蒂夫·賈伯斯 Steve Jobs" },
  { zh: "簡單，往往比複雜更難。", en: "Simple can be harder than complex.", by: "史蒂夫·賈伯斯 Steve Jobs" },
  { zh: "吸收有用的，捨棄沒用的，再加上屬於你自己的東西。", en: "Absorb what is useful, discard what is not, add what is uniquely your own.", by: "李小龍 Bruce Lee" },
  { zh: "我這輩子一再失敗，這正是我成功的原因。", en: "I've failed over and over and over again in my life. And that is why I succeed.", by: "麥可·喬丹 Michael Jordan" },
  { zh: "我能接受失敗，每個人都會在某些事上失敗，但我無法接受不去嘗試。", en: "I can accept failure, everyone fails at something. But I can't accept not trying.", by: "麥可·喬丹 Michael Jordan" },
  { zh: "最重要的是去激勵別人，讓他們在自己想做的事上成就偉大。", en: "The most important thing is to try and inspire people so that they can be great in whatever they want to do.", by: "柯比·布萊恩 Kobe Bryant" },
  { zh: "現在吃苦，然後用餘生當一名冠軍。", en: "Suffer now and live the rest of your life as a champion.", by: "穆罕默德·阿里 Muhammad Ali" },
  { zh: "我知道就算失敗也不會後悔，唯一可能讓我後悔的，是從來沒有嘗試過。", en: "I knew that if I failed I wouldn't regret that, but I knew the one thing I might regret is not ever trying.", by: "傑夫·貝佐斯 Jeff Bezos" },
  { zh: "當一件事重要到一定程度，就算勝算不高，你也會去做。", en: "When something is important enough, you do it even if the odds are not in your favor.", by: "伊隆·馬斯克 Elon Musk" },
  { zh: "把你的傷口，化成智慧。", en: "Turn your wounds into wisdom.", by: "歐普拉·溫芙蕾 Oprah Winfrey" },
  { zh: "我學到勇氣不是沒有恐懼，而是戰勝恐懼。", en: "I learned that courage was not the absence of fear, but the triumph over it.", by: "納爾遜·曼德拉 Nelson Mandela" },
  { zh: "你可能會遭遇許多挫敗，但絕不能被擊倒。", en: "You may encounter many defeats, but you must not be defeated.", by: "瑪雅·安傑洛 Maya Angelou" },
  { zh: "擁有活下去的「為什麼」的人，幾乎能承受任何「怎麼樣」。", en: "Those who have a 'why' to live, can bear with almost any 'how'.", by: "維克多·弗蘭克 Viktor Frankl" },
  { zh: "一個人的一切都可以被奪走，唯獨一樣不能：在任何處境下選擇自己態度的最後一項自由。", en: "Everything can be taken from a man but one thing: the last of the human freedoms—to choose one's attitude in any given set of circumstances.", by: "維克多·弗蘭克 Viktor Frankl" },
  { zh: "要進步就得改變；要完美，就得經常改變。", en: "To improve is to change; to be perfect is to change often.", by: "溫斯頓·邱吉爾 Winston Churchill" },
];
